import type { Session, TeaserContent, FullContent, InterviewQuestion } from "../types";

// AI generation service abstraction.
// TODO: Replace mock implementations with real AI provider calls (e.g. Claude API).

export async function generateTeaserContent(session: Session): Promise<TeaserContent> {
  const roleLabel = session.customRole || session.jobCategoryId;

  return {
    readinessSummary:
      `Based on your profile as a ${session.experienceLevel === "fresh" ? "fresh graduate" : "experienced professional"} applying for ${roleLabel}, you have a solid foundation. Focus on demonstrating relevant skills and genuine enthusiasm during your interview.`,
    previewQuestions: [
      "Tell me about yourself and why you're interested in this role.",
      `How would you handle a challenging situation specific to ${roleLabel}?`,
      "Describe a time when you went above and beyond for someone.",
    ],
    sampleAnswer:
      `When asked 'Tell me about yourself,' use the Present-Past-Future framework: Start with your current situation, mention relevant experience, then connect it to why this ${roleLabel} role excites you. Keep it under 2 minutes and practice until it sounds natural.`,
    tips: [
      "Research the company thoroughly — know their products, values, and recent news.",
      "Practice your answers out loud. Record yourself to check tone and pacing.",
      "Prepare 2-3 thoughtful questions to ask the interviewer at the end.",
    ],
  };
}

export async function generateFullContent(session: Session, isBundle: boolean): Promise<FullContent> {
  const roleLabel = session.customRole || session.jobCategoryId;

  const questions: InterviewQuestion[] = Array.from({ length: 15 }, (_, i) => ({
    id: `q-${i + 1}`,
    question: getMockQuestion(i, roleLabel),
    sampleAnswer: getMockAnswer(i, roleLabel),
    recruiterTrap: i % 3 === 1 ? getMockTrap(i) : undefined,
  }));

  const base: FullContent = {
    questions,
    tips: [
      "Research the company thoroughly before your interview.",
      "Practice STAR method answers for behavioral questions.",
      "Dress professionally even for virtual interviews.",
      "Test your internet connection before online interviews.",
      "Arrive 10-15 minutes early for in-person interviews.",
      "Bring extra copies of your resume.",
      "Maintain eye contact and positive body language.",
      "Send a thank-you message within 24 hours after the interview.",
    ],
    recruiterTraps: [
      "\"What's your expected salary?\" — Research market rates first. Give a range, not a fixed number.",
      "\"Why did you leave your last job?\" — Never badmouth a previous employer.",
      "\"Tell me about yourself\" — Keep it professional and under 2 minutes.",
      "\"What's your greatest weakness?\" — Give a real weakness with an improvement plan.",
      "\"Do you have any questions?\" — Always prepare at least 2 questions.",
    ],
  };

  if (isBundle) {
    base.resumeSuggestions = [
      "Lead with a strong professional summary highlighting key skills.",
      "Use action verbs: 'Managed,' 'Resolved,' 'Improved,' 'Achieved.'",
      `Quantify achievements relevant to ${roleLabel}.`,
      "Keep it to one page for entry-level, two pages max for experienced.",
      "Include relevant certifications and training.",
      "Tailor your resume for each application — match keywords from the job description.",
    ];
    base.coverLetter = generateMockCoverLetter(roleLabel);
    base.salaryScript = generateMockSalaryScript();
    base.practiceGuide = generateMockPracticeGuide();
  }

  return base;
}

function getMockQuestion(index: number, role: string): string {
  const templates = [
    "Tell me about yourself and why you're interested in this role.",
    `How would you handle a difficult situation in a ${role} context?`,
    "Describe a time when you went above and beyond.",
    "What do you know about our company?",
    "Why should we hire you over other candidates?",
    "How do you handle working in a fast-paced environment?",
    "What is your greatest weakness?",
    "Are you comfortable with shifting schedules?",
    "How would you deal with a difficult coworker?",
    "Where do you see yourself in 5 years?",
    "How do you handle repetitive tasks without losing motivation?",
    "Can you work independently without constant supervision?",
    `What does excellent performance mean to you in a ${role} role?`,
    "How do you handle multiple tasks at the same time?",
    "Do you have any questions for us?",
  ];
  return templates[index] || `Question ${index + 1} for ${role}`;
}

function getMockAnswer(index: number, role: string): string {
  return `[Strong sample answer for question ${index + 1} tailored to ${role}. This will be generated by AI in production.]`;
}

function getMockTrap(index: number): string {
  return `[Recruiter trap warning for question ${index + 1}. AI will generate context-specific warnings in production.]`;
}

function generateMockCoverLetter(role: string): string {
  return `Dear Hiring Manager,\n\nI am writing to express my strong interest in the ${role} position at [Company Name]. [This cover letter will be AI-generated and tailored to the specific role and experience level in production.]\n\nSincerely,\n[Your Name]`;
}

function generateMockSalaryScript(): string {
  return "1. Research market rates on JobStreet, Glassdoor, and Kalibrr.\n2. Let them make the first offer if possible.\n3. Give a range, not a fixed number.\n4. Consider the full package: HMO, allowances, bonuses.\n5. Never accept or reject immediately — ask for time to review.";
}

function generateMockPracticeGuide(): string[] {
  return [
    "Day 1: Read all 15 questions and answers. Highlight the most relevant ones.",
    "Day 2: Practice the top 5 questions out loud. Record and review yourself.",
    "Day 3: Research the company. Tailor your 'Tell me about yourself' answer.",
    "Day 4: Practice behavioral questions using the STAR method.",
    "Day 5: Do a mock interview with a friend or family member.",
    "Day 6: Review your resume and cover letter for alignment.",
    "Day 7: Final review. Prepare outfit, documents, and logistics.",
  ];
}
